dependencies:
  - python=3
  - pip:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - thinc
    - sklearn
    - tushare
    - time
    - datetime
    - random
    - pymysql
    - request
