dependencies:
  - python=3
  - pip:
    - datetime
    - ftplib
    - gc
    - math
    - matplotlib
    - matplotlib.pyplot
    - memory_profiler
    - numpy
    - os
    - pandas
    - pymysql
    - sklearn
    - sklearn.linear_model
    - socket
    - sys
    - time
    - tushare
    - random
    - request
